--
-- Copyright (C) 2012-2017 52°North Initiative for Geospatial Open Source
-- Software GmbH
--
-- This program is free software; you can redistribute it and/or modify it
-- under the terms of the GNU General Public License version 2 as published
-- by the Free Software Foundation.
--
-- If the program is linked with libraries which are licensed under one of
-- the following licenses, the combination of the program with the linked
-- library is not considered a "derivative work" of the program:
--
--     - Apache License, version 2.0
--     - Apache Software License, version 1.0
--     - GNU Lesser General Public License, version 3
--     - Mozilla Public License, versions 1.0, 1.1 and 2.0
--     - Common Development and Distribution License (CDDL), version 1.0
--
-- Therefore the distribution of the program linked with libraries licensed
-- under the aforementioned licenses, is permitted by the copyright holders
-- if the distribution is compliant with both the GNU General Public
-- License version 2 and the aforementioned licenses.
--
-- This program is distributed in the hope that it will be useful, but
-- WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
-- Public License for more details.
--

-- Database name to apply changes to
use sos
create table dbo.[procedure] (procedureId bigint identity not null, hibernateDiscriminator char(1) not null, procedureDescriptionFormatId bigint not null, identifier varchar(255) not null, codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), deleted char(1) default 'F' not null check (deleted in ('T','F')), disabled char(1) default 'F' not null check (disabled in ('T','F')), descriptionFile varchar(MAX), referenceFlag char(1) default 'F' check (referenceFlag in ('T','F')), typeOf bigint, isType char(1) default 'F' check (isType in ('T','F')), isAggregation char(1) default 'T' check (isAggregation in ('T','F')), mobile char(1) default 'F' check (mobile in ('T','F')), insitu char(1) default 'T' check (insitu in ('T','F')), primary key (procedureId));
create table dbo.address (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), id varchar(255), uuid varchar(255), city varchar(255), administrativeArea varchar(255), postalCode varchar(255), country varchar(255), primary key (pkid));
create table dbo.addressdeliveryPoint (addressId bigint not null, deliveryPoint varchar(255) not null, primary key (addressId, deliveryPoint));
create table dbo.addressemail (addressId bigint not null, electronicMailAddress varchar(255) not null, primary key (addressId, electronicMailAddress));
create table dbo.blobvalue (observationId bigint not null, value varbinary(MAX), primary key (observationId));
create table dbo.booleanfeatparamvalue (parameterId bigint not null, value char(1), primary key (parameterId), check (value in ('T','F')));
create table dbo.booleanparametervalue (parameterId bigint not null, value char(1), primary key (parameterId), check (value in ('T','F')));
create table dbo.booleanseriesparamvalue (parameterId bigint not null, value char(1), primary key (parameterId), check (value in ('T','F')));
create table dbo.booleanvalue (observationId bigint not null, value char(1), primary key (observationId), check (value in ('T','F')), check (value in ('T','F')));
create table dbo.categoryfeatparamvalue (parameterId bigint not null, value varchar(255), unitId bigint, primary key (parameterId));
create table dbo.categoryparametervalue (parameterId bigint not null, value varchar(255), unitId bigint, primary key (parameterId));
create table dbo.categoryseriesparamvalue (parameterId bigint not null, value varchar(255), unitId bigint, primary key (parameterId));
create table dbo.categoryvalue (observationId bigint not null, value varchar(255), identifier varchar(255), name varchar(255), description varchar(255), primary key (observationId));
create table dbo.codespace (codespaceId bigint identity not null, codespace varchar(255) not null, primary key (codespaceId));
create table dbo.complexvalue (observationId bigint not null, primary key (observationId));
create table dbo.compositeobservation (observationId bigint not null, childObservationId bigint not null, primary key (observationId, childObservationId));
create table dbo.compositephenomenon (parentObservablePropertyId bigint not null, childObservablePropertyId bigint not null, primary key (childObservablePropertyId, parentObservablePropertyId));
create table dbo.contact (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), id varchar(255), uuid varchar(255), phoneId bigint, addressId bigint, onlineresourceid bigint, hoursOfService varchar(255), contactInstructions varchar(255), primary key (pkid));
create table dbo.coordinatesystemaxis (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), identifier varchar(255), codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), remarks varchar(255), axisAbbrev varchar(255), codespaceAxisAbbrev bigint, axisDirection varchar(255), codespaceAxisDirection bigint, minimumValue double precision, maximumValue double precision, rangeMeaning varchar(255), codespaceRangeMeaning bigint, unitId bigint not null, primary key (pkid));
create table dbo.countfeatparamvalue (parameterId bigint not null, value int, primary key (parameterId));
create table dbo.countparametervalue (parameterId bigint not null, value int, primary key (parameterId));
create table dbo.countseriesparamvalue (parameterId bigint not null, value int, primary key (parameterId));
create table dbo.countvalue (observationId bigint not null, value int, primary key (observationId));
create table dbo.domainofvalidity (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), identifier varchar(255), codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), exExtentId bigint, primary key (pkid));
create table dbo.exextent (pkid bigint identity not null, id varchar(255), uuid varchar(255), description varchar(255), primary key (pkid));
create table dbo.exextentverticalext (exExtentId bigint not null, exVerticalExtentId bigint not null, primary key (exExtentId, exVerticalExtentId));
create table dbo.featureofinterest (featureOfInterestId bigint identity not null, hibernatediscriminator varchar(255), featureOfInterestTypeId bigint not null, identifier varchar(255), codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), geom GEOMETRY, descriptionXml varchar(MAX), url varchar(255), primary key (featureOfInterestId));
create table dbo.featureofinteresttype (featureOfInterestTypeId bigint identity not null, featureOfInterestType varchar(255) not null, primary key (featureOfInterestTypeId));
create table dbo.featureparameter (parameterId bigint identity not null, featureOfInterestId bigint not null, name varchar(255) not null, primary key (parameterId));
create table dbo.featurerelation (parentFeatureId bigint not null, childFeatureId bigint not null, primary key (childFeatureId, parentFeatureId));
create table dbo.geometryvalue (observationId bigint not null, value GEOMETRY, primary key (observationId));
create table dbo.i18nfeatureofinterest (id bigint identity not null, objectId bigint not null, locale varchar(255) not null, name varchar(255), description varchar(255), primary key (id));
create table dbo.i18nobservableproperty (id bigint identity not null, objectId bigint not null, locale varchar(255) not null, name varchar(255), description varchar(255), primary key (id));
create table dbo.i18noffering (id bigint identity not null, objectId bigint not null, locale varchar(255) not null, name varchar(255), description varchar(255), primary key (id));
create table dbo.i18nprocedure (id bigint identity not null, objectId bigint not null, locale varchar(255) not null, name varchar(255), description varchar(255), shortname varchar(255), longname varchar(255), primary key (id));
create table dbo.numericfeatparamvalue (parameterId bigint not null, value double precision, unitId bigint, primary key (parameterId));
create table dbo.numericparametervalue (parameterId bigint not null, value double precision, unitId bigint, primary key (parameterId));
create table dbo.numericseriesparamvalue (parameterId bigint not null, value double precision, unitId bigint, primary key (parameterId));
create table dbo.numericvalue (observationId bigint not null, value double precision, primary key (observationId));
create table dbo.observableproperty (observablePropertyId bigint identity not null, identifier varchar(255) not null, codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), disabled char(1) default 'F' not null check (disabled in ('T','F')), hiddenChild char(1) default 'F' not null check (hiddenChild in ('T','F')), primary key (observablePropertyId));
create table dbo.observation (observationId bigint identity not null, seriesId bigint not null, phenomenonTimeStart datetime2 not null, phenomenonTimeEnd datetime2 not null, resultTime datetime2 not null, identifier varchar(255), codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), deleted char(1) default 'F' not null check (deleted in ('T','F')), child char(1) default 'F' not null check (child in ('T','F')), parent char(1) default 'F' not null check (parent in ('T','F')), validTimeStart datetime2 default NULL, validTimeEnd datetime2 default NULL, samplingGeometry GEOMETRY, unitId bigint, primary key (observationId));
create table dbo.observationconstellation (observationConstellationId bigint identity not null, observablePropertyId bigint not null, procedureId bigint not null, observationTypeId bigint, offeringId bigint not null, deleted char(1) default 'F' not null check (deleted in ('T','F')), hiddenChild char(1) default 'F' not null check (hiddenChild in ('T','F')), disabled char(1) default 'F' not null check (disabled in ('T','F')), primary key (observationConstellationId));
create table dbo.observationhasoffering (observationId bigint not null, offeringId bigint not null, primary key (observationId, offeringId));
create table dbo.observationtype (observationTypeId bigint identity not null, observationType varchar(255) not null, primary key (observationTypeId));
create table dbo.offering (offeringId bigint identity not null, hibernateDiscriminator char(1) not null, identifier varchar(255) not null, codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), disabled char(1) default 'F' not null check (disabled in ('T','F')), primary key (offeringId));
create table dbo.offeringallowedfeaturetype (offeringId bigint not null, featureOfInterestTypeId bigint not null, primary key (offeringId, featureOfInterestTypeId));
create table dbo.offeringallowedobservationtype (offeringId bigint not null, observationTypeId bigint not null, primary key (offeringId, observationTypeId));
create table dbo.offeringhasrelatedfeature (relatedFeatureId bigint not null, offeringId bigint not null, primary key (offeringId, relatedFeatureId));
create table dbo.offeringrelation (parentOfferingId bigint not null, childOfferingId bigint not null, primary key (childOfferingId, parentOfferingId));
create table dbo.onlineresource (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), id varchar(255), uuid varchar(255), linkage varchar(255), protocol varchar(255), applicationProfile varchar(255), name varchar(255), description varchar(255), function varchar(255), primary key (pkid));
create table dbo.parameter (parameterId bigint identity not null, observationId bigint not null, name varchar(255) not null, primary key (parameterId));
create table dbo.phonefacsimile (phoneId bigint not null, facsimile varchar(255) not null, primary key (phoneId, facsimile));
create table dbo.phonevoice (phoneId bigint not null, voice varchar(255) not null, primary key (phoneId, voice));
create table dbo.proceduredescriptionformat (procedureDescriptionFormatId bigint identity not null, procedureDescriptionFormat varchar(255) not null, primary key (procedureDescriptionFormatId));
create table dbo.profileobservation (observationId bigint not null, childObservationId bigint not null, primary key (observationId, childObservationId));
create table dbo.profilevalue (observationId bigint not null, fromlevel double precision, tolevel double precision, levelunitid bigint, primary key (observationId));
create table dbo.relatedfeature (relatedFeatureId bigint identity not null, featureOfInterestId bigint not null, primary key (relatedFeatureId));
create table dbo.relatedfeaturehasrole (relatedFeatureId bigint not null, relatedFeatureRoleId bigint not null, primary key (relatedFeatureId, relatedFeatureRoleId));
create table dbo.relatedfeaturerole (relatedFeatureRoleId bigint identity not null, relatedFeatureRole varchar(255) not null, primary key (relatedFeatureRoleId));
create table dbo.relatedobservation (relatedObservationId bigint identity not null, observationId bigint, relatedObservation bigint, role varchar(255), relatedUrl varchar(255), primary key (relatedObservationId));
create table dbo.relatedseries (relationId bigint identity not null, seriesId bigint not null, relatedSeries bigint, role varchar(255), relatedUrl varchar(255), primary key (relationId));
create table dbo.responsibleparty (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), id varchar(255), uuid varchar(255), individualName varchar(255), organizationName varchar(255), positionName varchar(255), contactInfo bigint, ciRole bigint, primary key (pkid));
create table dbo.resulttemplate (resultTemplateId bigint identity not null, offeringId bigint not null, observablePropertyId bigint not null, procedureId bigint, featureOfInterestId bigint, identifier varchar(255) not null, resultStructure varchar(MAX) not null, resultEncoding varchar(MAX) not null, primary key (resultTemplateId));
create table dbo.role (pkid bigint identity not null, codeList varchar(255) not null, codeListValue varchar(255) not null, primary key (pkid));
create table dbo.sensorsystem (parentSensorId bigint not null, childSensorId bigint not null, primary key (childSensorId, parentSensorId));
create table dbo.series (seriesId bigint identity not null, featureOfInterestId bigint not null, observablePropertyId bigint not null, procedureId bigint not null, offeringId bigint not null, deleted char(1) default 'F' not null check (deleted in ('T','F')), published char(1) default 'T' not null check (published in ('T','F')), hiddenChild char(1) default 'F' not null check (hiddenChild in ('T','F')), firstTimeStamp datetime2 default NULL, lastTimeStamp datetime2 default NULL, firstNumericValue double precision, lastNumericValue double precision, unitId bigint, identifier varchar(255), codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), seriesType varchar(255), primary key (seriesId));
create table dbo.seriesmetadata (metadataId bigint identity not null, seriesId bigint not null, identifier varchar(255) not null, value varchar(255) not null, domain varchar(255) not null, primary key (metadataId));
create table dbo.seriesparameter (parameterId bigint identity not null, seriesId bigint not null, name varchar(255) not null, primary key (parameterId));
create table dbo.specimen (featureOfInterestId bigint not null, materialClass varchar(255) not null, samplingTimeStart datetime2 not null, samplingTimeEnd datetime2 not null, samplingMethod varchar(255), size double precision, sizeUnitId bigint, currentLocation varchar(255), specimenType varchar(255), primary key (featureOfInterestId));
create table dbo.swedataarrayvalue (observationId bigint not null, value varchar(MAX), primary key (observationId));
create table dbo.telephone (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), id varchar(255), uuid varchar(255), primary key (pkid));
create table dbo.textfeatparamvalue (parameterId bigint not null, value varchar(255), primary key (parameterId));
create table dbo.textparametervalue (parameterId bigint not null, value varchar(255), primary key (parameterId));
create table dbo.textseriesparamvalue (parameterId bigint not null, value varchar(255), primary key (parameterId));
create table dbo.textvalue (observationId bigint not null, value varchar(MAX), identifier varchar(255), name varchar(255), description varchar(255), primary key (observationId));
create table dbo.unit (unitId bigint identity not null, unit varchar(255) not null, name varchar(255), link varchar(255), primary key (unitId));
create table dbo.validproceduretime (validProcedureTimeId bigint identity not null, procedureId bigint not null, procedureDescriptionFormatId bigint not null, startTime datetime2 not null, endTime datetime2 default NULL, descriptionXml varchar(MAX) not null, primary key (validProcedureTimeId));
create table dbo.verticalcrs (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), identifier varchar(255), codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), remarks varchar(255), verticalCS bigint, verticalDatum bigint, primary key (pkid));
create table dbo.verticalcrscope (verticalcrsId bigint not null, scope varchar(255) not null, primary key (verticalcrsId, scope));
create table dbo.verticalcrsdomofval (verticalcrsId bigint not null, domainOfValidity bigint not null, primary key (verticalcrsId, domainOfValidity));
create table dbo.verticalcs (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), identifier varchar(255), codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), remarks varchar(255), aggregation varchar(255), primary key (pkid));
create table dbo.verticalcscoodsysaxis (verticalCSId bigint not null, coordinateSystemAxis bigint not null, primary key (verticalCSId, coordinateSystemAxis));
create table dbo.verticaldatum (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), identifier varchar(255), codespace bigint, name varchar(255), codespaceName bigint, description varchar(255), remarks varchar(255), domainOfValidityId bigint, anchorDefinition varchar(255), codespaceAnchorDef bigint, realizationEpoch datetime2 default NULL, primary key (pkid));
create table dbo.verticaldatumscope (verticalDatumId bigint not null, scope varchar(255) not null, primary key (verticalDatumId, scope));
create table dbo.verticalexextent (pkid bigint identity not null, nilReason varchar(255), href varchar(255), type varchar(255), role varchar(255), arcrole varchar(255), title varchar(255), show varchar(255), actuate varchar(255), remoteSchema varchar(255), id varchar(255), uuid varchar(255), minimumValue double precision, maximumValue double precision, verticalCRSId bigint, primary key (pkid));
create table dbo.wmlmonitoringpoint (featureOfInterestId bigint not null, primary key (featureOfInterestId));
create table dbo.wmlmprelatedparty (featureOfInterestId bigint not null, responsiblePartyId bigint not null, primary key (featureOfInterestId, responsiblePartyId));
create table dbo.wmlmpverticaldatum (featureOfInterestId bigint not null, verticalDatumId bigint not null, primary key (featureOfInterestId, verticalDatumId));
create table dbo.xmlfeatparamvalue (parameterId bigint not null, value varchar(MAX), primary key (parameterId));
create table dbo.xmlparametervalue (parameterId bigint not null, value varchar(MAX), primary key (parameterId));
create table dbo.xmlseriesparamvalue (parameterId bigint not null, value varchar(MAX), primary key (parameterId));
alter table dbo.[procedure] add constraint procIdentifierUK unique (identifier);
create index booleanFeatParamIdx on dbo.booleanfeatparamvalue (value);
create index booleanParamIdx on dbo.booleanparametervalue (value);
create index seriesBooleanParamIdx on dbo.booleanseriesparamvalue (value);
create index categoryFeatParamIdx on dbo.categoryfeatparamvalue (value);
create index categoryParamIdx on dbo.categoryparametervalue (value);
create index seriesCategoryParamIdx on dbo.categoryseriesparamvalue (value);
alter table dbo.codespace add constraint codespaceUK unique (codespace);
alter table dbo.coordinatesystemaxis add constraint csaIdentifierUK unique (identifier);
create index countFeatParamIdx on dbo.countfeatparamvalue (value);
create index countParamIdx on dbo.countparametervalue (value);
create index seriesCountParamIdx on dbo.countseriesparamvalue (value);
alter table dbo.domainofvalidity add constraint dovIdentifierUK unique (identifier);
alter table dbo.featureofinterest add constraint foiIdentifierUK unique (identifier);
alter table dbo.featureofinterest add constraint featureUrl unique (url);
;
alter table dbo.featureofinteresttype add constraint featureTypeUK unique (featureOfInterestType);
create index featParamNameIdx on dbo.featureparameter (name);
alter table dbo.i18nfeatureofinterest add constraint i18nFeatureIdentity unique (objectId, locale);
create index i18nFeatureIdx on dbo.i18nfeatureofinterest (objectId);
alter table dbo.i18nobservableproperty add constraint i18nobsPropIdentity unique (objectId, locale);
create index i18nObsPropIdx on dbo.i18nobservableproperty (objectId);
alter table dbo.i18noffering add constraint i18nOfferingIdentity unique (objectId, locale);
create index i18nOfferingIdx on dbo.i18noffering (objectId);
alter table dbo.i18nprocedure add constraint i18nProcedureIdentity unique (objectId, locale);
create index i18nProcedureIdx on dbo.i18nprocedure (objectId);
create index quantityFeatParamIdx on dbo.numericfeatparamvalue (value);
create index quantityParamIdx on dbo.numericparametervalue (value);
create index seriesQuantityParamIdx on dbo.numericseriesparamvalue (value);
alter table dbo.observableproperty add constraint obsPropIdentifierUK unique (identifier);
create index obsSeriesIdx on dbo.observation (seriesId);
create index obsPhenTimeStartIdx on dbo.observation (phenomenonTimeStart);
create index obsPhenTimeEndIdx on dbo.observation (phenomenonTimeEnd);
create index obsResultTimeIdx on dbo.observation (resultTime);
alter table dbo.observationconstellation add constraint obsnConstellationIdentity unique (observablePropertyId, procedureId, offeringId);
create index obsConstObsPropIdx on dbo.observationconstellation (observablePropertyId);
create index obsConstProcedureIdx on dbo.observationconstellation (procedureId);
create index obsConstOfferingIdx on dbo.observationconstellation (offeringId);
create index obshasoffobservationidx on dbo.observationhasoffering (observationId);
create index obshasoffofferingidx on dbo.observationhasoffering (offeringId);
alter table dbo.observationtype add constraint observationTypeUK unique (observationType);
alter table dbo.offering add constraint offIdentifierUK unique (identifier);
create index paramNameIdx on dbo.parameter (name);
alter table dbo.proceduredescriptionformat add constraint procDescFormatUK unique (procedureDescriptionFormat);
alter table dbo.relatedfeaturerole add constraint relFeatRoleUK unique (relatedFeatureRole);
create index relatedObsObsIdx on dbo.relatedobservation (observationId);
create index seriesRelationIdx on dbo.relatedseries (seriesId);
create index resultTempOfferingIdx on dbo.resulttemplate (offeringId);
create index resultTempeObsPropIdx on dbo.resulttemplate (observablePropertyId);
create index resultTempProcedureIdx on dbo.resulttemplate (procedureId);
create index resultTempIdentifierIdx on dbo.resulttemplate (identifier);
alter table dbo.series add constraint seriesIdentity unique (featureOfInterestId, observablePropertyId, procedureId, offeringId);
alter table dbo.series add constraint seriesIdentifierUK unique (identifier);
create index seriesFeatureIdx on dbo.series (featureOfInterestId);
create index seriesObsPropIdx on dbo.series (observablePropertyId);
create index seriesProcedureIdx on dbo.series (procedureId);
create index seriesOfferingIdx on dbo.series (offeringId);
create index seriesParamNameIdx on dbo.seriesparameter (name);
create index textFeatParamIdx on dbo.textfeatparamvalue (value);
create index textParamIdx on dbo.textparametervalue (value);
create index seriesTextParamIdx on dbo.textseriesparamvalue (value);
alter table dbo.unit add constraint unitUK unique (unit);
create index validProcedureTimeStartTimeIdx on dbo.validproceduretime (startTime);
create index validProcedureTimeEndTimeIdx on dbo.validproceduretime (endTime);
alter table dbo.verticalcrs add constraint vcrsIdentifierUK unique (identifier);
alter table dbo.verticalcs add constraint vcsIdentifierUK unique (identifier);
alter table dbo.verticaldatum add constraint vdIdentifierUK unique (identifier);
create index vddovIdx on dbo.verticaldatum (domainOfValidityId);
create index vevcrsIdx on dbo.verticalexextent (verticalCRSId);
create index seriesXmlParamIdx on dbo.xmlseriesparamvalue (value);
alter table dbo.[procedure] add constraint procProcDescFormatFk foreign key (procedureDescriptionFormatId) references dbo.proceduredescriptionformat;
alter table dbo.[procedure] add constraint procCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.[procedure] add constraint procCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.[procedure] add constraint typeOfFk foreign key (typeOf) references dbo.[procedure];
alter table dbo.addressdeliveryPoint add constraint adddelpoiFk foreign key (addressId) references dbo.address;
alter table dbo.addressemail add constraint addemailFk foreign key (addressId) references dbo.address;
alter table dbo.blobvalue add constraint observationBlobValueFk foreign key (observationId) references dbo.observation;
alter table dbo.booleanfeatparamvalue add constraint featParamBooleanValueFk foreign key (parameterId) references dbo.featureparameter;
alter table dbo.booleanparametervalue add constraint parameterBooleanValueFk foreign key (parameterId) references dbo.parameter;
alter table dbo.booleanseriesparamvalue add constraint seriesParamBooleanValueFk foreign key (parameterId) references dbo.seriesparameter;
alter table dbo.booleanvalue add constraint observationBooleanValueFk foreign key (observationId) references dbo.observation;
alter table dbo.categoryfeatparamvalue add constraint featParamCategoryValueFk foreign key (parameterId) references dbo.featureparameter;
alter table dbo.categoryfeatparamvalue add constraint catfeatparamvalueUnitFk foreign key (unitId) references dbo.unit;
alter table dbo.categoryparametervalue add constraint parameterCategoryValueFk foreign key (parameterId) references dbo.parameter;
alter table dbo.categoryparametervalue add constraint catParamValueUnitFk foreign key (unitId) references dbo.unit;
alter table dbo.categoryseriesparamvalue add constraint seriesParamCategoryValueFk foreign key (parameterId) references dbo.seriesparameter;
alter table dbo.categoryseriesparamvalue add constraint seriesCatParamValueUnitFk foreign key (unitId) references dbo.unit;
alter table dbo.categoryvalue add constraint observationCategoryValueFk foreign key (observationId) references dbo.observation;
alter table dbo.complexvalue add constraint observationComplexValueFk foreign key (observationId) references dbo.observation;
alter table dbo.compositeobservation add constraint observationChildFk foreign key (childObservationId) references dbo.observation;
alter table dbo.compositeobservation add constraint observationParentFK foreign key (observationId) references dbo.complexvalue;
alter table dbo.compositephenomenon add constraint observablePropertyChildFk foreign key (childObservablePropertyId) references dbo.observableproperty;
alter table dbo.compositephenomenon add constraint observablePropertyParentFk foreign key (parentObservablePropertyId) references dbo.observableproperty;
alter table dbo.contact add constraint contactphoneFk foreign key (phoneId) references dbo.telephone;
alter table dbo.contact add constraint contactaddressFk foreign key (addressId) references dbo.address;
alter table dbo.contact add constraint contactonlineresFk foreign key (onlineresourceid) references dbo.onlineresource;
alter table dbo.coordinatesystemaxis add constraint csaCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.coordinatesystemaxis add constraint csaCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.coordinatesystemaxis add constraint scsacodeaaFk foreign key (codespaceAxisAbbrev) references dbo.codespace;
alter table dbo.coordinatesystemaxis add constraint scsacodeadFk foreign key (codespaceAxisDirection) references dbo.codespace;
alter table dbo.coordinatesystemaxis add constraint scsacodermFk foreign key (codespaceRangeMeaning) references dbo.codespace;
alter table dbo.coordinatesystemaxis add constraint csaUnitFk foreign key (unitId) references dbo.unit;
alter table dbo.countfeatparamvalue add constraint featParamCountValueFk foreign key (parameterId) references dbo.featureparameter;
alter table dbo.countparametervalue add constraint parameterCountValueFk foreign key (parameterId) references dbo.parameter;
alter table dbo.countseriesparamvalue add constraint seriesParamCountValueFk foreign key (parameterId) references dbo.seriesparameter;
alter table dbo.countvalue add constraint observationCountValueFk foreign key (observationId) references dbo.observation;
alter table dbo.domainofvalidity add constraint codCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.domainofvalidity add constraint codCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.domainofvalidity add constraint dovexeFk foreign key (exExtentId) references dbo.exextent;
alter table dbo.exextentverticalext add constraint FK_qppk0ymn6peh5v1571aajqa8g foreign key (exVerticalExtentId) references dbo.verticalexextent;
alter table dbo.exextentverticalext add constraint exeexveFk foreign key (exExtentId) references dbo.exextent;
alter table dbo.featureofinterest add constraint featureFeatureTypeFk foreign key (featureOfInterestTypeId) references dbo.featureofinteresttype;
alter table dbo.featureofinterest add constraint featureCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.featureofinterest add constraint featureCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.featureparameter add constraint FK_4ps6yv41rwnbu3q0let2v7772 foreign key (featureOfInterestId) references dbo.featureofinterest;
alter table dbo.featurerelation add constraint featureOfInterestChildFk foreign key (childFeatureId) references dbo.featureofinterest;
alter table dbo.featurerelation add constraint featureOfInterestParentFk foreign key (parentFeatureId) references dbo.featureofinterest;
alter table dbo.geometryvalue add constraint observationGeometryValueFk foreign key (observationId) references dbo.observation;
alter table dbo.i18nfeatureofinterest add constraint i18nFeatureFeatureFk foreign key (objectId) references dbo.featureofinterest;
alter table dbo.i18nobservableproperty add constraint i18nObsPropObsPropFk foreign key (objectId) references dbo.observableproperty;
alter table dbo.i18noffering add constraint i18nOfferingOfferingFk foreign key (objectId) references dbo.offering;
alter table dbo.i18nprocedure add constraint i18nProcedureProcedureFk foreign key (objectId) references dbo.[procedure];
alter table dbo.numericfeatparamvalue add constraint featParamNumericValueFk foreign key (parameterId) references dbo.featureparameter;
alter table dbo.numericfeatparamvalue add constraint quanfeatparamvalueUnitFk foreign key (unitId) references dbo.unit;
alter table dbo.numericparametervalue add constraint parameterNumericValueFk foreign key (parameterId) references dbo.parameter;
alter table dbo.numericparametervalue add constraint quanParamValueUnitFk foreign key (unitId) references dbo.unit;
alter table dbo.numericseriesparamvalue add constraint seriesParamNumericValueFk foreign key (parameterId) references dbo.seriesparameter;
alter table dbo.numericseriesparamvalue add constraint seriesQuanParamValueUnitFk foreign key (unitId) references dbo.unit;
alter table dbo.numericvalue add constraint observationNumericValueFk foreign key (observationId) references dbo.observation;
alter table dbo.observableproperty add constraint obsPropCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.observableproperty add constraint obsPropCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.observation add constraint observationSeriesFk foreign key (seriesId) references dbo.series;
alter table dbo.observation add constraint obsCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.observation add constraint obsCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.observation add constraint observationUnitFk foreign key (unitId) references dbo.unit;
alter table dbo.observationconstellation add constraint obsConstObsPropFk foreign key (observablePropertyId) references dbo.observableproperty;
alter table dbo.observationconstellation add constraint obsnConstProcedureFk foreign key (procedureId) references dbo.[procedure];
alter table dbo.observationconstellation add constraint obsConstObservationIypeFk foreign key (observationTypeId) references dbo.observationtype;
alter table dbo.observationconstellation add constraint obsConstOfferingFk foreign key (offeringId) references dbo.offering;
alter table dbo.observationhasoffering add constraint observationOfferingFk foreign key (offeringId) references dbo.offering;
alter table dbo.observationhasoffering add constraint FK_s19siow5aetbwb8ppww4kb96n foreign key (observationId) references dbo.observation;
alter table dbo.offering add constraint offCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.offering add constraint offCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.offeringallowedfeaturetype add constraint offeringFeatureTypeFk foreign key (featureOfInterestTypeId) references dbo.featureofinteresttype;
alter table dbo.offeringallowedfeaturetype add constraint FK_cu8nfsf9q5vsn070o2d3u6chg foreign key (offeringId) references dbo.offering;
alter table dbo.offeringallowedobservationtype add constraint offeringObservationTypeFk foreign key (observationTypeId) references dbo.observationtype;
alter table dbo.offeringallowedobservationtype add constraint FK_jehw0637hllvta9ao1tqdhrtm foreign key (offeringId) references dbo.offering;
alter table dbo.offeringhasrelatedfeature add constraint relatedFeatureOfferingFk foreign key (offeringId) references dbo.offering;
alter table dbo.offeringhasrelatedfeature add constraint offeringRelatedFeatureFk foreign key (relatedFeatureId) references dbo.relatedfeature;
alter table dbo.offeringrelation add constraint offeringChildFk foreign key (childOfferingId) references dbo.offering;
alter table dbo.offeringrelation add constraint offeringParenfFk foreign key (parentOfferingId) references dbo.offering;
alter table dbo.parameter add constraint FK_3v5iovcndi9w0hgh827hcvivw foreign key (observationId) references dbo.observation;
alter table dbo.phonefacsimile add constraint phonefacsimilefk foreign key (phoneId) references dbo.telephone;
alter table dbo.phonevoice add constraint phonevoicefk foreign key (phoneId) references dbo.telephone;
alter table dbo.profileobservation add constraint profileObsChildFk foreign key (childObservationId) references dbo.observation;
alter table dbo.profileobservation add constraint profileObsParentFK foreign key (observationId) references dbo.profilevalue;
alter table dbo.profilevalue add constraint observationProfileValueFk foreign key (observationId) references dbo.observation;
alter table dbo.profilevalue add constraint profileUnitFk foreign key (levelunitid) references dbo.unit;
alter table dbo.relatedfeature add constraint relatedFeatureFeatureFk foreign key (featureOfInterestId) references dbo.featureofinterest;
alter table dbo.relatedfeaturehasrole add constraint relatedFeatRelatedFeatRoleFk foreign key (relatedFeatureRoleId) references dbo.relatedfeaturerole;
alter table dbo.relatedfeaturehasrole add constraint FK_5fd921q6mnbkc57mgm5g4uyyn foreign key (relatedFeatureId) references dbo.relatedfeature;
alter table dbo.relatedobservation add constraint FK_g0f0mpuxn3co65uwud4pwxh4q foreign key (observationId) references dbo.observation;
alter table dbo.relatedobservation add constraint FK_m4nuof4x6w253biuu1r6ttnqc foreign key (relatedObservation) references dbo.observation;
alter table dbo.relatedseries add constraint relatedSeriesFk foreign key (relatedSeries) references dbo.series;
alter table dbo.responsibleparty add constraint rpcontactFk foreign key (contactInfo) references dbo.contact;
alter table dbo.responsibleparty add constraint rproleFk foreign key (ciRole) references dbo.role;
alter table dbo.resulttemplate add constraint resultTemplateOfferingIdx foreign key (offeringId) references dbo.offering;
alter table dbo.resulttemplate add constraint resultTemplateObsPropFk foreign key (observablePropertyId) references dbo.observableproperty;
alter table dbo.resulttemplate add constraint resultTemplateProcedureFk foreign key (procedureId) references dbo.[procedure];
alter table dbo.resulttemplate add constraint resultTemplateFeatureIdx foreign key (featureOfInterestId) references dbo.featureofinterest;
alter table dbo.sensorsystem add constraint procedureChildFk foreign key (childSensorId) references dbo.[procedure];
alter table dbo.sensorsystem add constraint procedureParenfFk foreign key (parentSensorId) references dbo.[procedure];
alter table dbo.series add constraint seriesFeatureFk foreign key (featureOfInterestId) references dbo.featureofinterest;
alter table dbo.series add constraint seriesObPropFk foreign key (observablePropertyId) references dbo.observableproperty;
alter table dbo.series add constraint seriesProcedureFk foreign key (procedureId) references dbo.[procedure];
alter table dbo.series add constraint seriesOfferingFk foreign key (offeringId) references dbo.offering;
alter table dbo.series add constraint seriesUnitFk foreign key (unitId) references dbo.unit;
alter table dbo.series add constraint seriesCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.series add constraint seriesCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.specimen add constraint specimenFeatureFk foreign key (featureOfInterestId) references dbo.featureofinterest;
alter table dbo.specimen add constraint observationUnitFk foreign key (sizeUnitId) references dbo.unit;
alter table dbo.swedataarrayvalue add constraint observationSweDataArrayValueFk foreign key (observationId) references dbo.observation;
alter table dbo.textfeatparamvalue add constraint featParamTextValueFk foreign key (parameterId) references dbo.featureparameter;
alter table dbo.textparametervalue add constraint parameterTextValueFk foreign key (parameterId) references dbo.parameter;
alter table dbo.textseriesparamvalue add constraint seriesParamTextValueFk foreign key (parameterId) references dbo.seriesparameter;
alter table dbo.textvalue add constraint observationTextValueFk foreign key (observationId) references dbo.observation;
alter table dbo.validproceduretime add constraint validProcedureTimeProcedureFk foreign key (procedureId) references dbo.[procedure];
alter table dbo.validproceduretime add constraint validProcProcDescFormatFk foreign key (procedureDescriptionFormatId) references dbo.proceduredescriptionformat;
alter table dbo.verticalcrs add constraint vcrsCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.verticalcrs add constraint vcrsCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.verticalcrs add constraint vcrsvcsfk foreign key (verticalCS) references dbo.verticalcs;
alter table dbo.verticalcrs add constraint vcrsvdfk foreign key (verticalDatum) references dbo.verticaldatum;
alter table dbo.verticalcrscope add constraint vcrsscopefk foreign key (verticalcrsId) references dbo.verticalcrs;
alter table dbo.verticalcrsdomofval add constraint vcrsdovfk foreign key (domainOfValidity) references dbo.domainofvalidity;
alter table dbo.verticalcrsdomofval add constraint vcrsdovidfk foreign key (verticalcrsId) references dbo.verticalcrs;
alter table dbo.verticalcs add constraint vcsCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.verticalcs add constraint vcsCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.verticalcscoodsysaxis add constraint vcscsafk foreign key (coordinateSystemAxis) references dbo.coordinatesystemaxis;
alter table dbo.verticalcscoodsysaxis add constraint vcscsaidfk foreign key (verticalCSId) references dbo.verticalcs;
alter table dbo.verticaldatum add constraint vdCodespaceIdentifierFk foreign key (codespace) references dbo.codespace;
alter table dbo.verticaldatum add constraint vdCodespaceNameFk foreign key (codespaceName) references dbo.codespace;
alter table dbo.verticaldatum add constraint vddovFk foreign key (domainOfValidityId) references dbo.domainofvalidity;
alter table dbo.verticaldatum add constraint vdCodespaceADefFk foreign key (codespaceAnchorDef) references dbo.codespace;
alter table dbo.verticaldatumscope add constraint vdscopefk foreign key (verticalDatumId) references dbo.verticaldatum;
alter table dbo.verticalexextent add constraint vevcrsFk foreign key (verticalCRSId) references dbo.verticalcrs;
alter table dbo.wmlmonitoringpoint add constraint wmlmpFeatureFk foreign key (featureOfInterestId) references dbo.featureofinterest;
alter table dbo.wmlmprelatedparty add constraint wmlmprpFk foreign key (responsiblePartyId) references dbo.responsibleparty;
alter table dbo.wmlmprelatedparty add constraint FK_nyt2o5m81p35lqk7rctyook4o foreign key (featureOfInterestId) references dbo.featureofinterest;
alter table dbo.wmlmpverticaldatum add constraint FK_r4s9vt1g0o5o4lfi37qrh2yad foreign key (verticalDatumId) references dbo.verticaldatum;
alter table dbo.wmlmpverticaldatum add constraint wmlmpvdFk foreign key (featureOfInterestId) references dbo.featureofinterest;
alter table dbo.xmlfeatparamvalue add constraint featParamXmlValueFk foreign key (parameterId) references dbo.featureparameter;
alter table dbo.xmlparametervalue add constraint parameterXmlValueFk foreign key (parameterId) references dbo.parameter;
alter table dbo.xmlseriesparamvalue add constraint seriesParamXmlValueFk foreign key (parameterId) references dbo.seriesparameter;