--
-- Copyright (C) 2012-2020 52°North Initiative for Geospatial Open Source
-- Software GmbH
--
-- This program is free software; you can redistribute it and/or modify it
-- under the terms of the GNU General Public License version 2 as published
-- by the Free Software Foundation.
--
-- If the program is linked with libraries which are licensed under one of
-- the following licenses, the combination of the program with the linked
-- library is not considered a "derivative work" of the program:
--
--     - Apache License, version 2.0
--     - Apache Software License, version 1.0
--     - GNU Lesser General Public License, version 3
--     - Mozilla Public License, versions 1.0, 1.1 and 2.0
--     - Common Development and Distribution License (CDDL), version 1.0
--
-- Therefore the distribution of the program linked with libraries licensed
-- under the aforementioned licenses, is permitted by the copyright holders
-- if the distribution is compliant with both the GNU General Public
-- License version 2 and the aforementioned licenses.
--
-- This program is distributed in the hope that it will be useful, but
-- WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
-- Public License for more details.
--

create table public."procedure" (procedureId int8 not null, hibernateDiscriminator char(1) not null, procedureDescriptionFormatId int8 not null, identifier varchar(255) not null, codespace int8, name varchar(255), codespaceName int8, description varchar(255), deleted char(1) default 'F' not null check (deleted in ('T','F')), disabled char(1) default 'F' not null check (disabled in ('T','F')), descriptionFile text, referenceFlag char(1) default 'F' check (referenceFlag in ('T','F')), typeOf int8, isType char(1) default 'F' check (isType in ('T','F')), isAggregation char(1) default 'T' check (isAggregation in ('T','F')), mobile char(1) default 'F' check (mobile in ('T','F')), insitu char(1) default 'T' check (insitu in ('T','F')), primary key (procedureId));
comment on table public."procedure" is 'Table to store the procedure/sensor. Mapping file: mapping/core/Procedure.hbm.xml';
comment on column public."procedure".procedureId is 'Table primary key, used for relations';
comment on column public."procedure".procedureDescriptionFormatId is 'Relation/foreign key to the procedureDescriptionFormat table. Describes the format of the procedure description.';
comment on column public."procedure".identifier is 'The identifier of the procedure, gml:identifier. Used as parameter for queries. Unique';
comment on column public."procedure".codespace is 'Relation/foreign key to the codespace table. Contains the gml:identifier codespace. Optional';
comment on column public."procedure".name is 'The name of the procedure, gml:name. Optional';
comment on column public."procedure".codespaceName is 'Relation/foreign key to the codespace table. Contains the gml:name codespace. Optional';
comment on column public."procedure".description is 'Description of the procedure, gml:description. Optional';
comment on column public."procedure".deleted is 'Flag to indicate that this procedure is deleted or not (OGC SWES 2.0 - DeleteSensor operation)';
comment on column public."procedure".disabled is 'For later use by the SOS. Indicator if this procedure should not be provided by the SOS.';
comment on column public."procedure".descriptionFile is 'Field for full (XML) encoded procedure description or link to a procedure description file. Optional';
comment on column public."procedure".referenceFlag is 'Flag to indicate that this procedure is a reference procedure of another procedure. Not used by the SOS but by the Sensor Web REST-API';
comment on column public."procedure".typeOf is 'Relation/foreign key to procedure table. Optional, contains procedureId if this procedure is typeOf another procedure';
comment on column public."procedure".isType is 'Flag to indicate that this procedure is a type description, has no observations.';
comment on column public."procedure".isAggregation is 'Flag to indicate that this procedure is an aggregation (e.g. System, PhysicalSystem).';
comment on column public."procedure".mobile is 'Flag to indicate that this procedure is stationary (false) or mobile (true). Optional';
comment on column public."procedure".insitu is 'Flag to indicate that this procedure is insitu (true) or remote (false). Optional';
create table public.blobvalue (observationId int8 not null, value oid, primary key (observationId));
comment on table public.blobvalue is 'Value table for blob observation';
comment on column public.blobvalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.blobvalue.value is 'Blob observation value';
create table public.booleanfeatparamvalue (parameterId int8 not null, value char(1), primary key (parameterId), check (value in ('T','F')));
comment on table public.booleanfeatparamvalue is 'Value table for boolean parameter';
comment on column public.booleanfeatparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "featureParameter".parameterid';
comment on column public.booleanfeatparamvalue.value is 'Boolean parameter value';
create table public.booleanparametervalue (parameterId int8 not null, value char(1), primary key (parameterId), check (value in ('T','F')));
comment on table public.booleanparametervalue is 'Value table for boolean parameter';
comment on column public.booleanparametervalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "parameter".parameterid';
comment on column public.booleanparametervalue.value is 'Boolean parameter value';
create table public.booleanseriesparamvalue (parameterId int8 not null, value char(1), primary key (parameterId), check (value in ('T','F')));
comment on table public.booleanseriesparamvalue is 'Value table for boolean parameter';
comment on column public.booleanseriesparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the series parameter table. Contains seriesparameter.parameterid';
comment on column public.booleanseriesparamvalue.value is 'Boolean parameter value';
create table public.booleanvalue (observationId int8 not null, value char(1), primary key (observationId), check (value in ('T','F')), check (value in ('T','F')));
comment on table public.booleanvalue is 'Value table for boolean observation';
comment on column public.booleanvalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.booleanvalue.value is 'Boolean observation value';
create table public.categoryfeatparamvalue (parameterId int8 not null, value varchar(255), unitId int8, primary key (parameterId));
comment on table public.categoryfeatparamvalue is 'Value table for category parameter';
comment on column public.categoryfeatparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "featureParameter".parameterid';
comment on column public.categoryfeatparamvalue.value is 'Category parameter value';
comment on column public.categoryfeatparamvalue.unitId is 'Foreign Key (FK) to the related unit of measure. Contains "unit".unitid. Optional';
create table public.categoryparametervalue (parameterId int8 not null, value varchar(255), unitId int8, primary key (parameterId));
comment on table public.categoryparametervalue is 'Value table for category parameter';
comment on column public.categoryparametervalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "parameter".parameterid';
comment on column public.categoryparametervalue.value is 'Category parameter value';
comment on column public.categoryparametervalue.unitId is 'Foreign Key (FK) to the related unit of measure. Contains "unit".unitid. Optional';
create table public.categoryseriesparamvalue (parameterId int8 not null, value varchar(255), unitId int8, primary key (parameterId));
comment on table public.categoryseriesparamvalue is 'Value table for category parameter';
comment on column public.categoryseriesparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the series parameter table. Contains seriesparameter.parameterid';
comment on column public.categoryseriesparamvalue.value is 'Category parameter value';
comment on column public.categoryseriesparamvalue.unitId is 'Foreign Key (FK) to the related unit of measure. Contains "unit".unitid. Optional';
create table public.categoryvalue (observationId int8 not null, value varchar(255), identifier varchar(255), name varchar(255), description varchar(255), primary key (observationId));
comment on table public.categoryvalue is 'Value table for category observation';
comment on column public.categoryvalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.categoryvalue.value is 'Category observation value';
comment on column public.categoryvalue.identifier is 'SweCategory observation identifier';
comment on column public.categoryvalue.name is 'SweCategory observation name';
comment on column public.categoryvalue.description is 'SweCategory observation description';
create table public.codespace (codespaceId int8 not null, codespace varchar(255) not null, primary key (codespaceId));
comment on table public.codespace is 'Table to store the gml:identifier and gml:name codespace information. Mapping file: mapping/core/Codespace.hbm.xml';
comment on column public.codespace.codespaceId is 'Table primary key, used for relations';
comment on column public.codespace.codespace is 'The codespace value';
create table public.complexvalue (observationId int8 not null, primary key (observationId));
comment on table public.complexvalue is 'Value table for complex observation';
comment on column public.complexvalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
create table public.compositeobservation (observationId int8 not null, childObservationId int8 not null, primary key (observationId, childObservationId));
comment on table public.compositeobservation is 'Relation table for complex parent/child observations';
comment on column public.compositeobservation.observationId is 'Foreign Key (FK) to the related parent complex observation. Contains "observation".observationid';
comment on column public.compositeobservation.childObservationId is 'Foreign Key (FK) to the related child complex observation. Contains "observation".observationid';
create table public.compositephenomenon (parentObservablePropertyId int8 not null, childObservablePropertyId int8 not null, primary key (childObservablePropertyId, parentObservablePropertyId));
comment on table public.compositephenomenon is 'Relation table to store observableProperty hierarchies, aka compositePhenomenon. E.g. define a parent in a query and all childs are also contained in the response. Mapping file: mapping/transactional/TObservableProperty.hbm.xml';
comment on column public.compositephenomenon.parentObservablePropertyId is 'Foreign Key (FK) to the related parent observableProperty. Contains "observableProperty".observablePropertyid';
comment on column public.compositephenomenon.childObservablePropertyId is 'Foreign Key (FK) to the related child observableProperty. Contains "observableProperty".observablePropertyid';
create table public.countfeatparamvalue (parameterId int8 not null, value int4, primary key (parameterId));
comment on table public.countfeatparamvalue is 'Value table for count parameter';
comment on column public.countfeatparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "featureParameter".parameterid';
comment on column public.countfeatparamvalue.value is 'Count parameter value';
create table public.countparametervalue (parameterId int8 not null, value int4, primary key (parameterId));
comment on table public.countparametervalue is 'Value table for count parameter';
comment on column public.countparametervalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "parameter".parameterid';
comment on column public.countparametervalue.value is 'Count parameter value';
create table public.countseriesparamvalue (parameterId int8 not null, value int4, primary key (parameterId));
comment on table public.countseriesparamvalue is 'Value table for count parameter';
comment on column public.countseriesparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the series parameter table. Contains seriesparameter.parameterid';
comment on column public.countseriesparamvalue.value is 'Count parameter value';
create table public.countvalue (observationId int8 not null, value int4, primary key (observationId));
comment on table public.countvalue is 'Value table for count observation';
comment on column public.countvalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.countvalue.value is 'Count observation value';
create table public.featureofinterest (featureOfInterestId int8 not null, hibernatediscriminator varchar(255), featureOfInterestTypeId int8 not null, identifier varchar(255), codespace int8, name varchar(255), codespaceName int8, description varchar(255), geom GEOMETRY, descriptionXml text, url varchar(255), primary key (featureOfInterestId));
comment on column public.featureofinterest.featureOfInterestId is 'Table primary key, used for relations';
comment on column public.featureofinterest.featureOfInterestTypeId is 'Relation/foreign key to the featureOfInterestType table. Describes the type of the featureOfInterest. Contains "featureOfInterestType".featureOfInterestTypeId';
comment on column public.featureofinterest.identifier is 'The identifier of the featureOfInterest, gml:identifier. Used as parameter for queries. Optional but unique';
comment on column public.featureofinterest.codespace is 'Relation/foreign key to the codespace table. Contains the gml:identifier codespace. Optional';
comment on column public.featureofinterest.name is 'The name of the featureOfInterest, gml:name. Optional';
comment on column public.featureofinterest.codespaceName is 'The name of the featureOfInterest, gml:name. Optional';
comment on column public.featureofinterest.description is 'Description of the featureOfInterest, gml:description. Optional';
comment on column public.featureofinterest.geom is 'The geometry of the featureOfInterest (composed of the �latitude� and �longitude�) . Optional';
comment on column public.featureofinterest.descriptionXml is 'XML description of the feature, used when transactional profile is supported . Optional';
comment on column public.featureofinterest.url is 'Reference URL to the feature if it is stored in another service, e.g. WFS. Optional but unique';
create table public.featureofinteresttype (featureOfInterestTypeId int8 not null, featureOfInterestType varchar(255) not null, primary key (featureOfInterestTypeId));
comment on table public.featureofinteresttype is 'Table to store the FeatureOfInterestType information. Mapping file: mapping/core/FeatureOfInterestType.hbm.xml';
comment on column public.featureofinteresttype.featureOfInterestTypeId is 'Table primary key, used for relations';
comment on column public.featureofinteresttype.featureOfInterestType is 'The featureOfInterestType value, e.g. http://www.opengis.net/def/samplingFeatureType/OGC-OM/2.0/SF_SamplingPoint (OGC OM 2.0 specification) for point features';
create table public.featureparameter (parameterId int8 not null, featureOfInterestId int8 not null, name varchar(255) not null, primary key (parameterId));
comment on table public.featureparameter is 'Table to store additional featureOfInterest information (sf:parameter). Mapping file: mapping/core/FeatureParameter.hbm.xml';
comment on column public.featureparameter.parameterId is 'Table primary key';
comment on column public.featureparameter.featureOfInterestId is 'Foreign Key (FK) to the related featureOfInterest. Contains "featureOfInterest.featureOfInterestId';
comment on column public.featureparameter.name is 'Parameter name';
create table public.featurerelation (parentFeatureId int8 not null, childFeatureId int8 not null, primary key (childFeatureId, parentFeatureId));
comment on table public.featurerelation is 'Relation table to store feature hierarchies. E.g. define a parent in a query and all childs are also contained in the response. Mapping file: mapping/transactional/TFeatureOfInterest.hbm.xml';
comment on column public.featurerelation.parentFeatureId is 'Foreign Key (FK) to the related parent featureOfInterest. Contains "featureOfInterest".featureOfInterestid';
comment on column public.featurerelation.childFeatureId is 'Foreign Key (FK) to the related child featureOfInterest. Contains "featureOfInterest".featureOfInterestid';
create table public.geometryvalue (observationId int8 not null, value GEOMETRY, primary key (observationId));
comment on table public.geometryvalue is 'Value table for geometry observation';
comment on column public.geometryvalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.geometryvalue.value is 'Geometry observation value';
create table public.numericfeatparamvalue (parameterId int8 not null, value float8, unitId int8, primary key (parameterId));
comment on table public.numericfeatparamvalue is 'Value table for numeric/Measurment parameter';
comment on column public.numericfeatparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "featureParameter".parameterid';
comment on column public.numericfeatparamvalue.value is 'Numeric/Quantity parameter value';
comment on column public.numericfeatparamvalue.unitId is 'Foreign Key (FK) to the related unit of measure. Contains "unit".unitid. Optional';
create table public.numericparametervalue (parameterId int8 not null, value float8, unitId int8, primary key (parameterId));
comment on table public.numericparametervalue is 'Value table for numeric/Measurment parameter';
comment on column public.numericparametervalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "parameter".parameterid';
comment on column public.numericparametervalue.value is 'Numeric/Quantity parameter value';
comment on column public.numericparametervalue.unitId is 'Foreign Key (FK) to the related unit of measure. Contains "unit".unitid. Optional';
create table public.numericseriesparamvalue (parameterId int8 not null, value float8, unitId int8, primary key (parameterId));
comment on table public.numericseriesparamvalue is 'Value table for numeric/Measurment parameter';
comment on column public.numericseriesparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the series parameter table. Contains seriesparameter.parameterid';
comment on column public.numericseriesparamvalue.value is 'Numeric/Quantity parameter value';
comment on column public.numericseriesparamvalue.unitId is 'Foreign Key (FK) to the related unit of measure. Contains "unit".unitid. Optional';
create table public.numericvalue (observationId int8 not null, value float8, primary key (observationId));
comment on table public.numericvalue is 'Value table for numeric/Measurment observation';
comment on column public.numericvalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.numericvalue.value is 'Numeric/Measurment observation value';
create table public.observableproperty (observablePropertyId int8 not null, identifier varchar(255) not null, codespace int8, name varchar(255), codespaceName int8, description varchar(255), disabled char(1) default 'F' not null check (disabled in ('T','F')), hiddenChild char(1) default 'F' not null check (hiddenChild in ('T','F')), primary key (observablePropertyId));
comment on table public.observableproperty is 'Table to store the ObservedProperty/Phenomenon information. Mapping file: mapping/core/ObservableProperty.hbm.xml';
comment on column public.observableproperty.observablePropertyId is 'Table primary key, used for relations';
comment on column public.observableproperty.identifier is 'The identifier of the observableProperty, gml:identifier. Used as parameter for queries. Unique';
comment on column public.observableproperty.codespace is 'Relation/foreign key to the codespace table. Contains the gml:identifier codespace. Optional';
comment on column public.observableproperty.name is 'The name of the observableProperty, gml:name. Optional';
comment on column public.observableproperty.codespaceName is 'Relation/foreign key to the codespace table. Contains the gml:name codespace. Optional';
comment on column public.observableproperty.description is 'Description of the observableProperty, gml:description. Optional';
comment on column public.observableproperty.disabled is 'For later use by the SOS. Indicator if this observableProperty should not be provided by the SOS.';
create table public.observation (observationId int8 not null, seriesId int8 not null, phenomenonTimeStart timestamp not null, phenomenonTimeEnd timestamp not null, resultTime timestamp not null, identifier varchar(255), codespace int8, name varchar(255), codespaceName int8, description varchar(255), deleted char(1) default 'F' not null check (deleted in ('T','F')), child char(1) default 'F' not null check (child in ('T','F')), parent char(1) default 'F' not null check (parent in ('T','F')), validTimeStart timestamp default NULL, validTimeEnd timestamp default NULL, samplingGeometry GEOMETRY, unitId int8, primary key (observationId));
comment on table public.observation is 'Stores the observations. Mapping file: mapping/series/observation/ValuedObservation.hbm.xml';
comment on column public.observation.observationId is 'Table primary key, used in relations';
comment on column public.observation.seriesId is 'Relation/foreign key to the associated series table. Contains "series".seriesId';
comment on column public.observation.phenomenonTimeStart is 'Time stamp when the observation was started or phenomenon was observed';
comment on column public.observation.phenomenonTimeEnd is 'Time stamp when the observation was stopped or phenomenon was observed';
comment on column public.observation.resultTime is 'Time stamp when the observation was published or result was published/available';
comment on column public.observation.identifier is 'The identifier of the observation, gml:identifier. Used as parameter for queries. Optional but unique';
comment on column public.observation.codespace is 'Relation/foreign key to the codespace table. Contains the gml:identifier codespace. Optional';
comment on column public.observation.name is 'The name of the observation, gml:name. Optional';
comment on column public.observation.codespaceName is 'The name of the observation, gml:name. Optional';
comment on column public.observation.description is 'The name of the observation, gml:name. Optional';
comment on column public.observation.deleted is 'Flag to indicate that this observation is deleted or not (OGC SWES 2.0 - DeleteSensor operation or not specified DeleteObservation)';
comment on column public.observation.child is 'Flag to indicate that this observation is a child observation for complex observation';
comment on column public.observation.parent is 'Flag to indicate that this observation is a parent observation for complex observation';
comment on column public.observation.validTimeStart is 'Start time stamp for which the observation/result is valid, e.g. used for forecasting. Optional';
comment on column public.observation.validTimeEnd is 'End time stamp for which the observation/result is valid, e.g. used for forecasting. Optional';
comment on column public.observation.samplingGeometry is 'Sampling geometry describes exactly where the measurement has taken place. Used for OGC SOS 2.0 Spatial Filtering Profile. Optional';
comment on column public.observation.unitId is 'Foreign Key (FK) to the related unit of measure. Contains "unit".unitid. Optional';
create table public.observationconstellation (observationConstellationId int8 not null, observablePropertyId int8 not null, procedureId int8 not null, observationTypeId int8, offeringId int8 not null, deleted char(1) default 'F' not null check (deleted in ('T','F')), hiddenChild char(1) default 'F' not null check (hiddenChild in ('T','F')), disabled char(1) default 'F' not null check (disabled in ('T','F')), primary key (observationConstellationId));
comment on table public.observationconstellation is 'Table to store the ObservationConstellation information. Contains information about the constellation of observableProperty, procedure, offering and the observationType. Mapping file: mapping/core/ObservationConstellation.hbm.xml';
comment on column public.observationconstellation.observationConstellationId is 'Table primary key, used for relations';
comment on column public.observationconstellation.observablePropertyId is 'Foreign Key (FK) to the related observableProperty. Contains "observableproperty".observablepropertyid';
comment on column public.observationconstellation.procedureId is 'Foreign Key (FK) to the related procedure. Contains "procedure".procedureid';
comment on column public.observationconstellation.observationTypeId is 'Foreign Key (FK) to the related observation type. Contains "observationtype".observationtypeid';
comment on column public.observationconstellation.offeringId is 'Foreign Key (FK) to the related offering. Contains "offering".offeringid';
comment on column public.observationconstellation.deleted is 'Flag to indicate that this observationConstellation is deleted or not. Set if the related procedure is deleted via DeleteSensor operation (OGC SWES 2.0 - DeleteSensor operation)';
comment on column public.observationconstellation.hiddenChild is 'Flag to indicate that this observationConstellations procedure is a child procedure of another procedure. If true, the related procedure is not contained in OGC SOS 2.0 Capabilities but in OGC SOS 1.0.0 Capabilities.';
comment on column public.observationconstellation.disabled is 'Flag to indicate that this observationConstellations is disabled for insertion of observations. If false, new observation could be added to the SOS.';
create table public.observationtype (observationTypeId int8 not null, observationType varchar(255) not null, primary key (observationTypeId));
comment on table public.observationtype is 'Table to store the observationTypes. Mapping file: mapping/core/ObservationType.hbm.xml';
comment on column public.observationtype.observationTypeId is 'Table primary key, used for relations';
comment on column public.observationtype.observationType is 'The observationType value, e.g. http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement (OGC OM 2.0 specification) for OM_Measurement';
create table public.offering (offeringId int8 not null, hibernateDiscriminator char(1) not null, identifier varchar(255) not null, codespace int8, name varchar(255), codespaceName int8, description varchar(255), disabled char(1) default 'F' not null check (disabled in ('T','F')), primary key (offeringId));
comment on table public.offering is 'Table to store the offering information. Mapping file: mapping/core/Offering.hbm.xml';
comment on column public.offering.offeringId is 'Table primary key, used for relations';
comment on column public.offering.identifier is 'The identifier of the offering, gml:identifier. Used as parameter for queries. Unique';
comment on column public.offering.codespace is 'Relation/foreign key to the codespace table. Contains the gml:identifier codespace. Optional';
comment on column public.offering.name is 'The name of the offering, gml:name. If available, displyed in the contents of the Capabilites. Optional';
comment on column public.offering.codespaceName is 'Relation/foreign key to the codespace table. Contains the gml:name codespace. Optional';
comment on column public.offering.description is 'Description of the offering, gml:description. Optional';
comment on column public.offering.disabled is 'For later use by the SOS. Indicator if this offering should not be provided by the SOS.';
create table public.offeringallowedfeaturetype (offeringId int8 not null, featureOfInterestTypeId int8 not null, primary key (offeringId, featureOfInterestTypeId));
comment on table public.offeringallowedfeaturetype is 'Table to store relations between offering and allowed featureOfInterestTypes, defined in InsertSensor request. Mapping file: mapping/transactional/TOffering.hbm.xml';
comment on column public.offeringallowedfeaturetype.offeringId is 'Foreign Key (FK) to the related offering. Contains "offering".offeringid';
comment on column public.offeringallowedfeaturetype.featureOfInterestTypeId is 'Foreign Key (FK) to the related featureOfInterestTypeId. Contains "featureOfInterestType".featureOfInterestTypeId';
create table public.offeringallowedobservationtype (offeringId int8 not null, observationTypeId int8 not null, primary key (offeringId, observationTypeId));
comment on table public.offeringallowedobservationtype is 'Table to store relations between offering and allowed observationTypes, defined in InsertSensor request. Mapping file: mapping/transactional/TOffering.hbm.xml';
comment on column public.offeringallowedobservationtype.offeringId is 'Foreign Key (FK) to the related offering. Contains "offering".offeringid';
comment on column public.offeringallowedobservationtype.observationTypeId is 'Foreign Key (FK) to the related observationType. Contains "observationType".observationTypeId';
create table public.offeringhasrelatedfeature (relatedFeatureId int8 not null, offeringId int8 not null, primary key (offeringId, relatedFeatureId));
comment on table public.offeringhasrelatedfeature is 'Table to store relations between offering and associated relatedFeatures. Mapping file: mapping/transactional/TOffering.hbm.xml';
comment on column public.offeringhasrelatedfeature.relatedFeatureId is 'Foreign Key (FK) to the related relatedFeature. Contains "relatedFeature".relatedFeatureid';
comment on column public.offeringhasrelatedfeature.offeringId is 'Foreign Key (FK) to the related offering. Contains "offering".offeringid';
create table public.offeringrelation (parentOfferingId int8 not null, childOfferingId int8 not null, primary key (childOfferingId, parentOfferingId));
comment on table public.offeringrelation is 'Relation table to store offering hierarchies. E.g. define a parent in a query and all childs are also contained in the response. Mapping file: mapping/core/Offering.hbm.xml';
comment on column public.offeringrelation.parentOfferingId is 'Foreign Key (FK) to the related parent offering. Contains "offering".offeringid';
comment on column public.offeringrelation.childOfferingId is 'Foreign Key (FK) to the related child offering. Contains "offering".offeringid';
create table public.parameter (parameterId int8 not null, observationId int8 not null, name varchar(255) not null, primary key (parameterId));
comment on table public.parameter is 'Table to store additional obervation information (om:parameter). Mapping file: mapping/core/Parameter.hbm.xml';
comment on column public.parameter.parameterId is 'Table primary key';
comment on column public.parameter.observationId is 'Foreign Key (FK) to the related observation. Contains "observation".observationId';
comment on column public.parameter.name is 'Parameter name';
create table public.proceduredescriptionformat (procedureDescriptionFormatId int8 not null, procedureDescriptionFormat varchar(255) not null, primary key (procedureDescriptionFormatId));
comment on table public.proceduredescriptionformat is 'Table to store the ProcedureDescriptionFormat information of procedures. Mapping file: mapping/core/ProcedureDescriptionFormat.hbm.xml';
comment on column public.proceduredescriptionformat.procedureDescriptionFormatId is 'Table primary key, used for relations';
comment on column public.proceduredescriptionformat.procedureDescriptionFormat is 'The procedureDescriptionFormat value, e.g. http://www.opengis.net/sensorML/1.0.1 for procedures descriptions as specified in OGC SensorML 1.0.1';
create table public.profileobservation (observationId int8 not null, childObservationId int8 not null, primary key (observationId, childObservationId));
comment on table public.profileobservation is 'Relation table for complex parent/child observations';
comment on column public.profileobservation.observationId is 'Foreign Key (FK) to the related parent complex observation. Contains "observation".observationid';
comment on column public.profileobservation.childObservationId is 'Foreign Key (FK) to the related child complex observation. Contains "observation".observationid';
create table public.profilevalue (observationId int8 not null, fromlevel float8, tolevel float8, levelunitid int8, primary key (observationId));
comment on table public.profilevalue is 'Value table for profile observation';
comment on column public.profilevalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.profilevalue.fromlevel is 'Value of fromLevel';
comment on column public.profilevalue.tolevel is 'Value of toLevel';
comment on column public.profilevalue.levelunitid is 'Foreign Key (FK) to the related unit of measure. Contains "unit".unitid. Optional';
create table public.referencevalue (observationId int8 not null, href varchar(255), title varchar(255), role varchar(255), primary key (observationId));
comment on table public.referencevalue is 'Value table for category observation';
comment on column public.referencevalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.referencevalue.href is 'href value';
comment on column public.referencevalue.title is 'title value';
comment on column public.referencevalue.role is 'role value';
create table public.relatedfeature (relatedFeatureId int8 not null, featureOfInterestId int8 not null, primary key (relatedFeatureId));
comment on table public.relatedfeature is 'Table to store related feature information used in the OGC SOS 2.0 Capabilities (See also OGC SWES 2.0). Mapping file: mapping/transactionl/RelatedFeature.hbm.xml';
comment on column public.relatedfeature.relatedFeatureId is 'Table primary key, used for relations';
comment on column public.relatedfeature.featureOfInterestId is 'Foreign Key (FK) to the related featureOfInterest. Contains "featureOfInterest".featureOfInterestid';
create table public.relatedfeaturehasrole (relatedFeatureId int8 not null, relatedFeatureRoleId int8 not null, primary key (relatedFeatureId, relatedFeatureRoleId));
comment on table public.relatedfeaturehasrole is 'Relation table to store relatedFeatures and their associated relatedFeatureRoles. Mapping file: mapping/transactionl/RelatedFeature.hbm.xml';
comment on column public.relatedfeaturehasrole.relatedFeatureId is 'Foreign Key (FK) to the related relatedFeature. Contains "relatedFeature".relatedFeatureid';
comment on column public.relatedfeaturehasrole.relatedFeatureRoleId is 'Foreign Key (FK) to the related relatedFeatureRole. Contains "relatedFeatureRole".relatedFeatureRoleid';
create table public.relatedfeaturerole (relatedFeatureRoleId int8 not null, relatedFeatureRole varchar(255) not null, primary key (relatedFeatureRoleId));
comment on table public.relatedfeaturerole is 'Table to store related feature role information used in the OGC SOS 2.0 Capabilities (See also OGC SWES 2.0). Mapping file: mapping/transactionl/RelatedFeatureRole.hbm.xml';
comment on column public.relatedfeaturerole.relatedFeatureRoleId is 'Table primary key, used for relations';
comment on column public.relatedfeaturerole.relatedFeatureRole is 'The related feature role definition. See OGC SWES 2.0 specification';
create table public.relatedobservation (relatedObservationId int8 not null, observationId int8, relatedObservation int8, role varchar(255), relatedUrl varchar(255), primary key (relatedObservationId));
comment on table public.relatedobservation is 'The related observation of an observation.';
comment on column public.relatedobservation.relatedObservationId is 'Table primary key';
comment on column public.relatedobservation.observationId is 'Foreign Key (FK) to the observation. Contains "observation".observationId';
comment on column public.relatedobservation.relatedObservation is 'Relation/foreign key to the associated observation table. Contains "observation".observationId';
comment on column public.relatedobservation.role is 'The role of the relation';
comment on column public.relatedobservation.relatedUrl is 'An url to a related observation';
create table public.relatedseries (relationId int8 not null, seriesId int8 not null, relatedSeries int8, role varchar(255), relatedUrl varchar(255), primary key (relationId));
comment on table public.relatedseries is 'The series relation should be used if the series table represents a timeseries.';
comment on column public.relatedseries.relationId is 'Table primary key';
comment on column public.relatedseries.seriesId is 'Foreign Key (FK) to the series. Contains "series".seriesId';
comment on column public.relatedseries.relatedSeries is 'Relation/foreign key to the associated series table. Contains "series".seriesId';
comment on column public.relatedseries.role is 'The role of the relation';
comment on column public.relatedseries.relatedUrl is 'An url to a related observation';
create table public.resulttemplate (resultTemplateId int8 not null, offeringId int8 not null, observablePropertyId int8 not null, procedureId int8, featureOfInterestId int8, identifier varchar(255) not null, resultStructure text not null, resultEncoding text not null, primary key (resultTemplateId));
comment on table public.resulttemplate is 'Table to store resultTemplates (OGC SOS 2.0 result handling profile). Mapping file: mapping/transactionl/ResultTemplate.hbm.xml';
comment on column public.resulttemplate.resultTemplateId is 'Table primary key';
comment on column public.resulttemplate.offeringId is 'Foreign Key (FK) to the related offering. Contains "offering".offeringid';
comment on column public.resulttemplate.observablePropertyId is 'Foreign Key (FK) to the related observableProperty. Contains "observableProperty".observablePropertyId';
comment on column public.resulttemplate.procedureId is 'Foreign Key (FK) to the related procedure. Contains "procedure".procedureId';
comment on column public.resulttemplate.featureOfInterestId is 'Foreign Key (FK) to the related featureOfInterest. Contains "featureOfInterest".featureOfInterestid';
comment on column public.resulttemplate.identifier is 'The resultTemplate identifier, required for InsertResult requests.';
comment on column public.resulttemplate.resultStructure is 'The resultStructure as XML string. Describes the types and order of the values in a GetResultResponse/InsertResultRequest';
comment on column public.resulttemplate.resultEncoding is 'The resultEncoding as XML string. Describes the encoding of the values in a GetResultResponse/InsertResultRequest';
create table public.sensorsystem (parentSensorId int8 not null, childSensorId int8 not null, primary key (childSensorId, parentSensorId));
comment on table public.sensorsystem is 'Relation table to store procedure hierarchies. E.g. define a parent in a query and all childs are also contained in the response. Mapping file: mapping/transactional/TProcedure.hbm.xml';
comment on column public.sensorsystem.parentSensorId is 'Foreign Key (FK) to the related parent procedure. Contains "procedure".procedureid';
comment on column public.sensorsystem.childSensorId is 'Foreign Key (FK) to the related child procedure. Contains "procedure".procedureid';
create table public.series (seriesId int8 not null, featureOfInterestId int8 not null, observablePropertyId int8 not null, procedureId int8 not null, offeringId int8 not null, deleted char(1) default 'F' not null check (deleted in ('T','F')), published char(1) default 'T' not null check (published in ('T','F')), hiddenChild char(1) default 'F' not null check (hiddenChild in ('T','F')), firstTimeStamp timestamp default NULL, lastTimeStamp timestamp default NULL, firstNumericValue float8, lastNumericValue float8, unitId int8, identifier varchar(255), codespace int8, name varchar(255), codespaceName int8, description varchar(255), seriesType varchar(255), primary key (seriesId));
comment on table public.series is 'Table to store a (time-) series which consists of featureOfInterest, observableProperty, and procedure. Mapping file: mapping/series/Series.hbm.xml';
comment on column public.series.seriesId is 'Table primary key, used for relations';
comment on column public.series.featureOfInterestId is 'Foreign Key (FK) to the related featureOfInterest. Contains "featureOfInterest".featureOfInterestId';
comment on column public.series.observablePropertyId is 'Foreign Key (FK) to the related observableProperty. Contains "observableproperty".observablepropertyid';
comment on column public.series.procedureId is 'Foreign Key (FK) to the related procedure. Contains "procedure".procedureid';
comment on column public.series.offeringId is 'Foreign Key (FK) to the related offering. Contains "offering".offeringid';
comment on column public.series.deleted is 'Flag to indicate that this series is deleted or not. Set if the related procedure is deleted via DeleteSensor operation (OGC SWES 2.0 - DeleteSensor operation)';
comment on column public.series.published is 'Flag to indicate that this series is published or not. A not published series is not contained in GetObservation and GetDataAvailability responses';
comment on column public.series.hiddenChild is 'TODO';
comment on column public.series.firstTimeStamp is 'The time stamp of the first (temporal) observation associated to this series';
comment on column public.series.lastTimeStamp is 'The time stamp of the last (temporal) observation associated to this series';
comment on column public.series.firstNumericValue is 'The value of the first (temporal) observation associated to this series';
comment on column public.series.lastNumericValue is 'The value of the last (temporal) observation associated to this series';
comment on column public.series.unitId is 'Foreign Key (FK) to the related unit of the first/last numeric values . Contains "unit".unitid';
comment on column public.series.identifier is 'The identifier of the series, gml:identifier. Unique';
comment on column public.series.codespace is 'Relation/foreign key to the codespace table. Contains the gml:identifier codespace. Optional';
comment on column public.series.name is 'The name of the series, gml:name. Optional';
comment on column public.series.codespaceName is 'Relation/foreign key to the codespace table. Contains the gml:name codespace. Optional';
comment on column public.series.description is 'Description of the series, gml:description. Optional';
comment on column public.series.seriesType is 'Definition of the series type, e.g. measurement for OM_Measurement. Optional';
create table public.seriesmetadata (metadataId int8 not null, seriesId int8 not null, identifier varchar(255) not null, value varchar(255) not null, domain varchar(255) not null, primary key (metadataId));
comment on column public.seriesmetadata.metadataId is 'Table primary key, used for relations';
comment on column public.seriesmetadata.seriesId is 'Foreign Key (FK) to the related series. Contains "series".seriesId';
comment on column public.seriesmetadata.identifier is 'The identifier of the metadata value.';
comment on column public.seriesmetadata.value is 'The metadata value.';
comment on column public.seriesmetadata.domain is 'The metadata value domain.';
create table public.seriesparameter (parameterId int8 not null, seriesId int8 not null, name varchar(255) not null, primary key (parameterId));
comment on table public.seriesparameter is 'Table to store additional obervation information (om:parameter). Mapping file: mapping/series/metadata/SeriesParameter.hbm.xml';
comment on column public.seriesparameter.parameterId is 'Table primary key';
comment on column public.seriesparameter.seriesId is 'Foreign Key (FK) to the related series. Contains "series".seriesId';
comment on column public.seriesparameter.name is 'Parameter name';
create table public.seriesreference (seriesid int8 not null, referenceseriesid int8 not null, sortorder int4 not null, primary key (seriesid, sortorder));
comment on column public.seriesreference.seriesid is 'Foreign Key (FK) to link a series with a reference value series. Contains "series".seriesid';
comment on column public.seriesreference.referenceseriesid is 'Foreign Key (FK) to the linked reference value series. Contains "series".seriesid';
create table public.swedataarrayvalue (observationId int8 not null, value text, primary key (observationId));
comment on table public.swedataarrayvalue is 'Value table for SweDataArray observation';
comment on column public.swedataarrayvalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.swedataarrayvalue.value is 'SweDataArray observation value';
create table public.textfeatparamvalue (parameterId int8 not null, value varchar(255), primary key (parameterId));
comment on table public.textfeatparamvalue is 'Value table for text parameter';
comment on column public.textfeatparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "featureParameter".parameterid';
comment on column public.textfeatparamvalue.value is 'Text parameter value';
create table public.textparametervalue (parameterId int8 not null, value varchar(255), primary key (parameterId));
comment on table public.textparametervalue is 'Value table for text parameter';
comment on column public.textparametervalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "parameter".parameterid';
comment on column public.textparametervalue.value is 'Text parameter value';
create table public.textseriesparamvalue (parameterId int8 not null, value varchar(255), primary key (parameterId));
comment on table public.textseriesparamvalue is 'Value table for text parameter';
comment on column public.textseriesparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the series parameter table. Contains seriesparameter.parameterid';
comment on column public.textseriesparamvalue.value is 'Text parameter value';
create table public.textvalue (observationId int8 not null, value text, identifier varchar(255), name varchar(255), description varchar(255), primary key (observationId));
comment on table public.textvalue is 'Value table for text observation';
comment on column public.textvalue.observationId is 'Foreign Key (FK) to the related observation from the observation table. Contains "observation".observationid';
comment on column public.textvalue.value is 'Text observation value';
comment on column public.textvalue.identifier is 'SweText observation identifier';
comment on column public.textvalue.name is 'SweText observation name';
comment on column public.textvalue.description is 'SweText observation description';
create table public.unit (unitId int8 not null, unit varchar(255) not null, name varchar(255), link varchar(255), primary key (unitId));
comment on table public.unit is 'Table to store the unit of measure information, used in observations. Mapping file: mapping/core/Unit.hbm.xml';
comment on column public.unit.unitId is 'Table primary key, used for relations';
comment on column public.unit.unit is 'The unit of measure of observations. See http://unitsofmeasure.org/ucum.html';
comment on column public.unit.name is 'The name of the unit of measure of observations';
comment on column public.unit.link is 'The link to an external description of the unit of measure of observations, e.g. a vocabulary';
create table public.validproceduretime (validProcedureTimeId int8 not null, procedureId int8 not null, procedureDescriptionFormatId int8 not null, startTime timestamp not null, endTime timestamp default NULL, descriptionXml text not null, primary key (validProcedureTimeId));
comment on table public.validproceduretime is 'Table to store procedure descriptions which were inserted or updated via the transactional Profile. Mapping file: mapping/transactionl/ValidProcedureTime.hbm.xml';
comment on column public.validproceduretime.validProcedureTimeId is 'Table primary key';
comment on column public.validproceduretime.procedureId is 'Foreign Key (FK) to the related procedure. Contains "procedure".procedureid';
comment on column public.validproceduretime.procedureDescriptionFormatId is 'Foreign Key (FK) to the related procedureDescriptionFormat. Contains "procedureDescriptionFormat".procedureDescriptionFormatid';
comment on column public.validproceduretime.startTime is 'Timestamp since this procedure description is valid';
comment on column public.validproceduretime.endTime is 'Timestamp until this procedure description is invalid';
comment on column public.validproceduretime.descriptionXml is 'Procedure description as XML string';
create table public.xmlfeatparamvalue (parameterId int8 not null, value text, primary key (parameterId));
comment on table public.xmlfeatparamvalue is 'Value table for XML parameter';
comment on column public.xmlfeatparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "featureParameter".parameterid';
comment on column public.xmlfeatparamvalue.value is 'XML parameter value';
create table public.xmlparametervalue (parameterId int8 not null, value text, primary key (parameterId));
comment on table public.xmlparametervalue is 'Value table for XML parameter';
comment on column public.xmlparametervalue.parameterId is 'Foreign Key (FK) to the related parameter from the parameter table. Contains "parameter".parameterid';
comment on column public.xmlparametervalue.value is 'XML parameter value';
create table public.xmlseriesparamvalue (parameterId int8 not null, value text, primary key (parameterId));
comment on table public.xmlseriesparamvalue is 'Value table for XML parameter';
comment on column public.xmlseriesparamvalue.parameterId is 'Foreign Key (FK) to the related parameter from the series parameter table. Contains seriesparameter.parameterid';
comment on column public.xmlseriesparamvalue.value is 'XML parameter value';
alter table public."procedure" add constraint procIdentifierUK unique (identifier);
create index blobvalueobsididx on public.blobvalue (observationId);
create index booleanFeatParamIdx on public.booleanfeatparamvalue (value);
create index booleanparamididx on public.booleanparametervalue (parameterId);
create index booleanParamIdx on public.booleanparametervalue (value);
create index booleanseriesparamididx on public.booleanseriesparamvalue (parameterId);
create index seriesBooleanParamIdx on public.booleanseriesparamvalue (value);
create index booleanvalueobsididx on public.booleanvalue (observationId);
create index booleanvalueidx on public.booleanvalue (value);
create index categoryFeatParamIdx on public.categoryfeatparamvalue (value);
create index categoryparamididx on public.categoryparametervalue (parameterId);
create index categoryParamIdx on public.categoryparametervalue (value);
create index categoryseriesparamididx on public.categoryseriesparamvalue (parameterId);
create index seriesCategoryParamIdx on public.categoryseriesparamvalue (value);
create index categoryvalueobsididx on public.categoryvalue (observationId);
create index categoryvalueidx on public.categoryvalue (value);
alter table public.codespace add constraint codespaceUK unique (codespace);
create index complexvalueobsididx on public.complexvalue (observationId);
create index complexobsididx on public.compositeobservation (observationId);
create index complexchildobsididx on public.compositeobservation (childObservationId);
create index countFeatParamIdx on public.countfeatparamvalue (value);
create index countparamididx on public.countparametervalue (parameterId);
create index countParamIdx on public.countparametervalue (value);
create index countseriesparamididx on public.countseriesparamvalue (parameterId);
create index seriesCountParamIdx on public.countseriesparamvalue (value);
create index countvalueobsididx on public.countvalue (observationId);
create index countvalueidx on public.countvalue (value);
alter table public.featureofinterest add constraint foiIdentifierUK unique (identifier);
alter table public.featureofinterest add constraint featureUrl unique (url);
create index featureGeomIdx on public.featureofinterest USING GIST (geom);
alter table public.featureofinteresttype add constraint featureTypeUK unique (featureOfInterestType);
create index featParamNameIdx on public.featureparameter (name);
create index geometryvalueobsididx on public.geometryvalue (observationId);
create index geometryvalueidx on public.geometryvalue USING GIST (value);
create index quantityFeatParamIdx on public.numericfeatparamvalue (value);
create index numericparamididx on public.numericparametervalue (parameterId);
create index quantityParamIdx on public.numericparametervalue (value);
create index numericseriesparamididx on public.numericseriesparamvalue (parameterId);
create index seriesQuantityParamIdx on public.numericseriesparamvalue (value);
create index numericvalueobsididx on public.numericvalue (observationId);
create index numericvalueidx on public.numericvalue (value);
alter table public.observableproperty add constraint obsPropIdentifierUK unique (identifier);
create index obsSeriesIdx on public.observation (seriesId);
create index obsPhenTimeStartIdx on public.observation (phenomenonTimeStart);
create index obsPhenTimeEndIdx on public.observation (phenomenonTimeEnd);
create index obsResultTimeIdx on public.observation (resultTime);
create index samplingGeomIdx on public.observation USING GIST (samplingGeometry);
alter table public.observationconstellation add constraint obsnConstellationIdentity unique (observablePropertyId, procedureId, offeringId);
create index obsConstObsPropIdx on public.observationconstellation (observablePropertyId);
create index obsConstProcedureIdx on public.observationconstellation (procedureId);
create index obsConstOfferingIdx on public.observationconstellation (offeringId);
alter table public.observationtype add constraint observationTypeUK unique (observationType);
alter table public.offering add constraint offIdentifierUK unique (identifier);
create index paramNameIdx on public.parameter (name);
alter table public.proceduredescriptionformat add constraint procDescFormatUK unique (procedureDescriptionFormat);
create index profileobsididx on public.profileobservation (observationId, childObservationId);
create index profvalueobsididx on public.profilevalue (observationId);
create index referencevalueobsididx on public.referencevalue (observationId);
alter table public.relatedfeaturerole add constraint relFeatRoleUK unique (relatedFeatureRole);
create index relobsobsididx on public.relatedobservation (observationId);
create index relobsrelobsididx on public.relatedobservation (relatedObservation);
create index relatedObsObsIdx on public.relatedobservation (observationId);
create index seriesRelationIdx on public.relatedseries (seriesId);
create index resultTempOfferingIdx on public.resulttemplate (offeringId);
create index resultTempeObsPropIdx on public.resulttemplate (observablePropertyId);
create index resultTempProcedureIdx on public.resulttemplate (procedureId);
create index resultTempIdentifierIdx on public.resulttemplate (identifier);
alter table public.series add constraint seriesIdentity unique (featureOfInterestId, observablePropertyId, procedureId, offeringId);
alter table public.series add constraint seriesIdentifierUK unique (identifier);
create index seriesFeatureIdx on public.series (featureOfInterestId);
create index seriesObsPropIdx on public.series (observablePropertyId);
create index seriesProcedureIdx on public.series (procedureId);
create index seriesOfferingIdx on public.series (offeringId);
create index seriesmetadataseriesididx on public.seriesmetadata (seriesId);
create index seriesParamNameIdx on public.seriesparameter (name);
create index seriesididx on public.seriesreference (seriesid);
create index referenceseriesididx on public.seriesreference (referenceseriesid);
create index swedataarryvalueobsididx on public.swedataarrayvalue (observationId);
create index textFeatParamIdx on public.textfeatparamvalue (value);
create index textparamididx on public.textparametervalue (parameterId);
create index textParamIdx on public.textparametervalue (value);
create index textseriesparamididx on public.textseriesparamvalue (parameterId);
create index seriesTextParamIdx on public.textseriesparamvalue (value);
create index textvalueobsididx on public.textvalue (observationId);
create index textvalueidx on public.textvalue (value);
alter table public.unit add constraint unitUK unique (unit);
create index validProcedureTimeStartTimeIdx on public.validproceduretime (startTime);
create index validProcedureTimeEndTimeIdx on public.validproceduretime (endTime);
create index xmlparamididx on public.xmlparametervalue (parameterId);
create index xmlseriesparamididx on public.xmlseriesparamvalue (parameterId);
create index seriesXmlParamIdx on public.xmlseriesparamvalue (value);
alter table public."procedure" add constraint procProcDescFormatFk foreign key (procedureDescriptionFormatId) references public.proceduredescriptionformat;
alter table public."procedure" add constraint procCodespaceIdentifierFk foreign key (codespace) references public.codespace;
alter table public."procedure" add constraint procCodespaceNameFk foreign key (codespaceName) references public.codespace;
alter table public."procedure" add constraint typeOfFk foreign key (typeOf) references public."procedure";
alter table public.blobvalue add constraint observationBlobValueFk foreign key (observationId) references public.observation;
alter table public.booleanfeatparamvalue add constraint featParamBooleanValueFk foreign key (parameterId) references public.featureparameter;
alter table public.booleanparametervalue add constraint parameterBooleanValueFk foreign key (parameterId) references public.parameter;
alter table public.booleanseriesparamvalue add constraint seriesParamBooleanValueFk foreign key (parameterId) references public.seriesparameter;
alter table public.booleanvalue add constraint observationBooleanValueFk foreign key (observationId) references public.observation;
alter table public.categoryfeatparamvalue add constraint featParamCategoryValueFk foreign key (parameterId) references public.featureparameter;
alter table public.categoryfeatparamvalue add constraint catfeatparamvalueUnitFk foreign key (unitId) references public.unit;
alter table public.categoryparametervalue add constraint parameterCategoryValueFk foreign key (parameterId) references public.parameter;
alter table public.categoryparametervalue add constraint catParamValueUnitFk foreign key (unitId) references public.unit;
alter table public.categoryseriesparamvalue add constraint seriesParamCategoryValueFk foreign key (parameterId) references public.seriesparameter;
alter table public.categoryseriesparamvalue add constraint seriesCatParamValueUnitFk foreign key (unitId) references public.unit;
alter table public.categoryvalue add constraint observationCategoryValueFk foreign key (observationId) references public.observation;
alter table public.complexvalue add constraint observationComplexValueFk foreign key (observationId) references public.observation;
alter table public.compositeobservation add constraint observationChildFk foreign key (childObservationId) references public.observation;
alter table public.compositeobservation add constraint observationParentFK foreign key (observationId) references public.complexvalue;
alter table public.compositephenomenon add constraint observablePropertyChildFk foreign key (childObservablePropertyId) references public.observableproperty;
alter table public.compositephenomenon add constraint observablePropertyParentFk foreign key (parentObservablePropertyId) references public.observableproperty;
alter table public.countfeatparamvalue add constraint featParamCountValueFk foreign key (parameterId) references public.featureparameter;
alter table public.countparametervalue add constraint parameterCountValueFk foreign key (parameterId) references public.parameter;
alter table public.countseriesparamvalue add constraint seriesParamCountValueFk foreign key (parameterId) references public.seriesparameter;
alter table public.countvalue add constraint observationCountValueFk foreign key (observationId) references public.observation;
alter table public.featureofinterest add constraint featureFeatureTypeFk foreign key (featureOfInterestTypeId) references public.featureofinteresttype;
alter table public.featureofinterest add constraint featureCodespaceIdentifierFk foreign key (codespace) references public.codespace;
alter table public.featureofinterest add constraint featureCodespaceNameFk foreign key (codespaceName) references public.codespace;
alter table public.featureparameter add constraint FK_4ps6yv41rwnbu3q0let2v7772 foreign key (featureOfInterestId) references public.featureofinterest;
alter table public.featurerelation add constraint featureOfInterestChildFk foreign key (childFeatureId) references public.featureofinterest;
alter table public.featurerelation add constraint featureOfInterestParentFk foreign key (parentFeatureId) references public.featureofinterest;
alter table public.geometryvalue add constraint observationGeometryValueFk foreign key (observationId) references public.observation;
alter table public.numericfeatparamvalue add constraint featParamNumericValueFk foreign key (parameterId) references public.featureparameter;
alter table public.numericfeatparamvalue add constraint quanfeatparamvalueUnitFk foreign key (unitId) references public.unit;
alter table public.numericparametervalue add constraint parameterNumericValueFk foreign key (parameterId) references public.parameter;
alter table public.numericparametervalue add constraint quanParamValueUnitFk foreign key (unitId) references public.unit;
alter table public.numericseriesparamvalue add constraint seriesParamNumericValueFk foreign key (parameterId) references public.seriesparameter;
alter table public.numericseriesparamvalue add constraint seriesQuanParamValueUnitFk foreign key (unitId) references public.unit;
alter table public.numericvalue add constraint observationNumericValueFk foreign key (observationId) references public.observation;
alter table public.observableproperty add constraint obsPropCodespaceIdentifierFk foreign key (codespace) references public.codespace;
alter table public.observableproperty add constraint obsPropCodespaceNameFk foreign key (codespaceName) references public.codespace;
alter table public.observation add constraint observationSeriesFk foreign key (seriesId) references public.series;
alter table public.observation add constraint obsCodespaceIdentifierFk foreign key (codespace) references public.codespace;
alter table public.observation add constraint obsCodespaceNameFk foreign key (codespaceName) references public.codespace;
alter table public.observation add constraint observationUnitFk foreign key (unitId) references public.unit;
alter table public.observationconstellation add constraint obsConstObsPropFk foreign key (observablePropertyId) references public.observableproperty;
alter table public.observationconstellation add constraint obsnConstProcedureFk foreign key (procedureId) references public."procedure";
alter table public.observationconstellation add constraint obsConstObservationIypeFk foreign key (observationTypeId) references public.observationtype;
alter table public.observationconstellation add constraint obsConstOfferingFk foreign key (offeringId) references public.offering;
alter table public.offering add constraint offCodespaceIdentifierFk foreign key (codespace) references public.codespace;
alter table public.offering add constraint offCodespaceNameFk foreign key (codespaceName) references public.codespace;
alter table public.offeringallowedfeaturetype add constraint offeringFeatureTypeFk foreign key (featureOfInterestTypeId) references public.featureofinteresttype;
alter table public.offeringallowedfeaturetype add constraint FK_cu8nfsf9q5vsn070o2d3u6chg foreign key (offeringId) references public.offering;
alter table public.offeringallowedobservationtype add constraint offeringObservationTypeFk foreign key (observationTypeId) references public.observationtype;
alter table public.offeringallowedobservationtype add constraint FK_jehw0637hllvta9ao1tqdhrtm foreign key (offeringId) references public.offering;
alter table public.offeringhasrelatedfeature add constraint relatedFeatureOfferingFk foreign key (offeringId) references public.offering;
alter table public.offeringhasrelatedfeature add constraint offeringRelatedFeatureFk foreign key (relatedFeatureId) references public.relatedfeature;
alter table public.offeringrelation add constraint offeringChildFk foreign key (childOfferingId) references public.offering;
alter table public.offeringrelation add constraint offeringParenfFk foreign key (parentOfferingId) references public.offering;
alter table public.parameter add constraint FK_3v5iovcndi9w0hgh827hcvivw foreign key (observationId) references public.observation;
alter table public.profileobservation add constraint profileObsChildFk foreign key (childObservationId) references public.observation;
alter table public.profileobservation add constraint profileObsParentFK foreign key (observationId) references public.profilevalue;
alter table public.profilevalue add constraint observationProfileValueFk foreign key (observationId) references public.observation;
alter table public.profilevalue add constraint profileUnitFk foreign key (levelunitid) references public.unit;
alter table public.referencevalue add constraint observationRefValueFk foreign key (observationId) references public.observation;
alter table public.relatedfeature add constraint relatedFeatureFeatureFk foreign key (featureOfInterestId) references public.featureofinterest;
alter table public.relatedfeaturehasrole add constraint relatedFeatRelatedFeatRoleFk foreign key (relatedFeatureRoleId) references public.relatedfeaturerole;
alter table public.relatedfeaturehasrole add constraint FK_5fd921q6mnbkc57mgm5g4uyyn foreign key (relatedFeatureId) references public.relatedfeature;
alter table public.relatedobservation add constraint FK_g0f0mpuxn3co65uwud4pwxh4q foreign key (observationId) references public.observation;
alter table public.relatedobservation add constraint FK_m4nuof4x6w253biuu1r6ttnqc foreign key (relatedObservation) references public.observation;
alter table public.relatedseries add constraint relatedSeriesFk foreign key (relatedSeries) references public.series;
alter table public.resulttemplate add constraint resultTemplateOfferingIdx foreign key (offeringId) references public.offering;
alter table public.resulttemplate add constraint resultTemplateObsPropFk foreign key (observablePropertyId) references public.observableproperty;
alter table public.resulttemplate add constraint resultTemplateProcedureFk foreign key (procedureId) references public."procedure";
alter table public.resulttemplate add constraint resultTemplateFeatureIdx foreign key (featureOfInterestId) references public.featureofinterest;
alter table public.sensorsystem add constraint procedureChildFk foreign key (childSensorId) references public."procedure";
alter table public.sensorsystem add constraint procedureParenfFk foreign key (parentSensorId) references public."procedure";
alter table public.series add constraint seriesFeatureFk foreign key (featureOfInterestId) references public.featureofinterest;
alter table public.series add constraint seriesObPropFk foreign key (observablePropertyId) references public.observableproperty;
alter table public.series add constraint seriesProcedureFk foreign key (procedureId) references public."procedure";
alter table public.series add constraint seriesOfferingFk foreign key (offeringId) references public.offering;
alter table public.series add constraint seriesUnitFk foreign key (unitId) references public.unit;
alter table public.series add constraint seriesCodespaceIdentifierFk foreign key (codespace) references public.codespace;
alter table public.series add constraint seriesCodespaceNameFk foreign key (codespaceName) references public.codespace;
alter table public.seriesreference add constraint seriesrefreffk foreign key (referenceseriesid) references public.series;
alter table public.seriesreference add constraint seriesrefseriesfk foreign key (seriesid) references public.series;
alter table public.swedataarrayvalue add constraint observationSweDataArrayValueFk foreign key (observationId) references public.observation;
alter table public.textfeatparamvalue add constraint featParamTextValueFk foreign key (parameterId) references public.featureparameter;
alter table public.textparametervalue add constraint parameterTextValueFk foreign key (parameterId) references public.parameter;
alter table public.textseriesparamvalue add constraint seriesParamTextValueFk foreign key (parameterId) references public.seriesparameter;
alter table public.textvalue add constraint observationTextValueFk foreign key (observationId) references public.observation;
alter table public.validproceduretime add constraint validProcedureTimeProcedureFk foreign key (procedureId) references public."procedure";
alter table public.validproceduretime add constraint validProcProcDescFormatFk foreign key (procedureDescriptionFormatId) references public.proceduredescriptionformat;
alter table public.xmlfeatparamvalue add constraint featParamXmlValueFk foreign key (parameterId) references public.featureparameter;
alter table public.xmlparametervalue add constraint parameterXmlValueFk foreign key (parameterId) references public.parameter;
alter table public.xmlseriesparamvalue add constraint seriesParamXmlValueFk foreign key (parameterId) references public.seriesparameter;
create sequence public.codespaceId_seq;
create sequence public.featureOfInterestId_seq;
create sequence public.featureOfInterestTypeId_seq;
create sequence public.metadataId_seq;
create sequence public.observablePropertyId_seq;
create sequence public.observationConstellationId_seq;
create sequence public.observationId_seq;
create sequence public.observationTypeId_seq;
create sequence public.offeringId_seq;
create sequence public.parameterId_seq;
create sequence public.procDescFormatId_seq;
create sequence public.procedureId_seq;
create sequence public.relatedFeatureId_seq;
create sequence public.relatedFeatureRoleId_seq;
create sequence public.relatedObservationId_seq;
create sequence public.resultTemplateId_seq;
create sequence public.seriesId_seq;
create sequence public.seriesRelationId_seq;
create sequence public.unitId_seq;
create sequence public.validProcedureTimeId_seq;